from abc import ABC, abstractmethod
from uuid import UUID

from app.domain.entities.adoption import AdoptionApplication
from app.domain.entities.cat import Cat
from app.domain.entities.donation import DonationIntent, DonationPost
from app.domain.entities.foster import FosterApplication
from app.domain.entities.partner import Partner, PartnerNegotiation
from app.domain.entities.user import FosterProfile, Host, ProtectorProfile, User


class UserRepository(ABC):
    @abstractmethod
    async def save(self, user: User) -> User: ...
    @abstractmethod
    async def find_by_email(self, email: str) -> User | None: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> User | None: ...
    @abstractmethod
    async def increment_token_version(self, user_id: UUID) -> None: ...
    @abstractmethod
    async def save_protector_profile(self, profile: ProtectorProfile) -> ProtectorProfile: ...
    @abstractmethod
    async def save_foster_profile(self, profile: FosterProfile) -> FosterProfile: ...
    @abstractmethod
    async def find_protector_profile(self, user_id: UUID) -> ProtectorProfile | None: ...
    @abstractmethod
    async def find_foster_profile(self, user_id: UUID) -> FosterProfile | None: ...
    @abstractmethod
    async def update_protector_profile(self, profile: ProtectorProfile) -> ProtectorProfile: ...
    @abstractmethod
    async def update_foster_profile(self, profile: FosterProfile) -> FosterProfile: ...
    @abstractmethod
    async def find_hosts(self) -> list[Host]: ...


class CatRepository(ABC):
    @abstractmethod
    async def save(self, cat: Cat) -> Cat: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> Cat | None: ...
    @abstractmethod
    async def find_all(self, filters: dict) -> list[Cat]: ...
    @abstractmethod
    async def delete(self, id: UUID) -> None: ...
    @abstractmethod
    async def find_by_protector(self, protector_id: UUID) -> list[Cat]: ...


class AdoptionRepository(ABC):
    @abstractmethod
    async def save(self, application: AdoptionApplication) -> AdoptionApplication: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> AdoptionApplication | None: ...
    @abstractmethod
    async def find_by_cat(self, cat_id: UUID) -> list[AdoptionApplication]: ...
    @abstractmethod
    async def find_by_protector_cats(self, protector_id: UUID) -> list[AdoptionApplication]: ...


class FosterApplicationRepository(ABC):
    @abstractmethod
    async def save(self, application: FosterApplication) -> FosterApplication: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> FosterApplication | None: ...
    @abstractmethod
    async def find_by_user(self, user_id: UUID) -> list[FosterApplication]: ...
    @abstractmethod
    async def find_all(self) -> list[FosterApplication]: ...


class DonationPostRepository(ABC):
    @abstractmethod
    async def save(self, post: DonationPost) -> DonationPost: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> DonationPost | None: ...
    @abstractmethod
    async def find_all(self, filters: dict) -> list[DonationPost]: ...
    @abstractmethod
    async def save_intent(self, intent: DonationIntent) -> DonationIntent: ...
    @abstractmethod
    async def find_intents_by_protector(self, protector_id: UUID) -> list[DonationIntent]: ...


class PartnerRepository(ABC):
    @abstractmethod
    async def save(self, partner: Partner) -> Partner: ...
    @abstractmethod
    async def find_all(self) -> list[Partner]: ...
    @abstractmethod
    async def find_by_id(self, id: UUID) -> Partner | None: ...
    @abstractmethod
    async def find_by_location(self, lat: float, lng: float, radius: float) -> list[Partner]: ...
    @abstractmethod
    async def delete(self, id: UUID) -> None: ...
    @abstractmethod
    async def save_negotiation(self, negotiation: PartnerNegotiation) -> PartnerNegotiation: ...
    @abstractmethod
    async def find_negotiation_by_id(self, id: UUID) -> PartnerNegotiation | None: ...
    @abstractmethod
    async def find_negotiations_by_host(self, host_id: UUID) -> list[PartnerNegotiation]: ...
